// <auto-generated />
using System;
using DavidStudio.Core.Essentials.CompleteSample.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DavidStudio.Core.Essentials.CompleteSample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121175852_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DavidStudio.Core.Essentials.CompleteSample.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IncorporationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9a85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            IncorporationDateUtc = new DateTime(1976, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("eaa85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            IncorporationDateUtc = new DateTime(1938, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("eba85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            IncorporationDateUtc = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi"
                        });
                });

            modelBuilder.Entity("DavidStudio.Core.Essentials.CompleteSample.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eca85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            CreatedAtUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            ManufacturerId = new Guid("e9a85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            ModifiedAtUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iPhone 17",
                            Price = 1199m,
                            StockCount = 1000
                        },
                        new
                        {
                            Id = new Guid("eda85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            CreatedAtUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            ManufacturerId = new Guid("e9a85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            ModifiedAtUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iPhone 16",
                            Price = 999m,
                            StockCount = 50
                        },
                        new
                        {
                            Id = new Guid("eea85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            CreatedAtUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            ManufacturerId = new Guid("eaa85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            ModifiedAtUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S25",
                            Price = 600m,
                            StockCount = 25
                        },
                        new
                        {
                            Id = new Guid("efa85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            CreatedAtUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            ManufacturerId = new Guid("eba85b6d-b003-46af-ad15-69b1a6cbdd7c"),
                            ModifiedAtUtc = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi 17 Pro Max",
                            Price = 1500m,
                            StockCount = 10
                        });
                });

            modelBuilder.Entity("DavidStudio.Core.Essentials.CompleteSample.Entities.Product", b =>
                {
                    b.HasOne("DavidStudio.Core.Essentials.CompleteSample.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
